# Generated by Django 5.2.16 on 2026-07-15 10:35

from django.db import migrations, models
from django.db.models import Q


def migrate_roles_to_admin_and_user(apps, schema_editor):
    User = apps.get_model("auth", "User")
    AdminProfile = apps.get_model("accounts", "AdminProfile")

    legacy_profiles = AdminProfile.objects.filter(role__in=("reviewer", "staff"))
    legacy_user_ids = list(legacy_profiles.values_list("user_id", flat=True))
    legacy_profiles.update(role="user")
    User.objects.filter(pk__in=legacy_user_ids, is_superuser=False).update(is_staff=False)

    admin_users = User.objects.filter(
        Q(is_superuser=True) | Q(is_staff=True, admin_profile__isnull=True)
    )
    for user in admin_users.iterator():
        AdminProfile.objects.update_or_create(
            user_id=user.pk,
            defaults={"role": "admin"},
        )
        if not user.is_staff:
            User.objects.filter(pk=user.pk).update(is_staff=True)


def restore_legacy_staff_role(apps, schema_editor):
    User = apps.get_model("auth", "User")
    AdminProfile = apps.get_model("accounts", "AdminProfile")

    user_profile_ids = list(
        AdminProfile.objects.filter(role="user").values_list("user_id", flat=True)
    )
    AdminProfile.objects.filter(role="user").update(role="staff")
    User.objects.filter(pk__in=user_profile_ids).update(is_staff=True)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            migrate_roles_to_admin_and_user,
            restore_legacy_staff_role,
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=24),
        ),
    ]
