# Generated by Django 5.2.16 on 2026-07-25 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_backfill_approved_member_telephones'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('contact', 'Contact'), ('application', 'Application'), ('subscriber', 'Subscriber')], db_index=True, max_length=24)),
                ('title', models.CharField(max_length=180)),
                ('message', models.TextField(max_length=1000)),
                ('source_type', models.CharField(db_index=True, max_length=64)),
                ('source_id', models.PositiveBigIntegerField()),
                ('target_url', models.CharField(max_length=500)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['recipient', 'is_read', 'created_at'], name='admin_notif_rec_read_idx'), models.Index(fields=['recipient', 'notification_type', 'created_at'], name='admin_notif_rec_type_idx'), models.Index(fields=['source_type', 'source_id'], name='admin_notif_source_idx')],
                'constraints': [models.UniqueConstraint(fields=('recipient', 'notification_type', 'source_type', 'source_id'), name='uniq_admin_notification_source_recipient')],
            },
        ),
    ]
