# Generated by Django 5.2.16 on 2026-07-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_adminnotification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminnotification',
            name='notification_type',
            field=models.CharField(choices=[('contact', 'Contact'), ('application', 'Application'), ('bursary_application', 'Bursary application'), ('subscriber', 'Subscriber'), ('support', 'Support')], db_index=True, max_length=24),
        ),
    ]
