# Generated by Django 5.2.16 on 2026-07-25 07:49

import django.db.models.deletion
import ipc_backend.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(default='main', max_length=40, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hero', models.JSONField(default=dict, validators=[ipc_backend.validators.validate_content_section])),
                ('value_intro', models.JSONField(default=dict, validators=[ipc_backend.validators.validate_content_section])),
                ('values', models.JSONField(default=dict, validators=[ipc_backend.validators.validate_content_section])),
                ('pathways_intro', models.JSONField(default=dict, validators=[ipc_backend.validators.validate_content_section])),
                ('pathways', models.JSONField(default=dict, validators=[ipc_backend.validators.validate_content_section])),
                ('capability_model', models.JSONField(default=dict, validators=[ipc_backend.validators.validate_content_section])),
                ('evidence', models.JSONField(default=dict, validators=[ipc_backend.validators.validate_content_section])),
                ('impact', models.JSONField(default=dict, validators=[ipc_backend.validators.validate_content_section])),
                ('faq', models.JSONField(default=dict, validators=[ipc_backend.validators.validate_content_section])),
                ('final_cta', models.JSONField(default=dict, validators=[ipc_backend.validators.validate_content_section])),
                ('seo', models.JSONField(default=dict, validators=[ipc_backend.validators.validate_content_section])),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employer Content',
                'verbose_name_plural': 'Employer Content',
                'db_table': 'employer_content',
            },
        ),
        migrations.CreateModel(
            name='PartnershipContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(default='main', max_length=40, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hero', models.JSONField(default=dict, validators=[ipc_backend.validators.validate_content_section])),
                ('partner_types', models.JSONField(default=dict, validators=[ipc_backend.validators.validate_content_section])),
                ('value', models.JSONField(default=dict, validators=[ipc_backend.validators.validate_content_section])),
                ('comparison', models.JSONField(default=dict, validators=[ipc_backend.validators.validate_content_section])),
                ('integrity', models.JSONField(default=dict, validators=[ipc_backend.validators.validate_content_section])),
                ('process', models.JSONField(default=dict, validators=[ipc_backend.validators.validate_content_section])),
                ('faq', models.JSONField(default=dict, validators=[ipc_backend.validators.validate_content_section])),
                ('final_cta', models.JSONField(default=dict, validators=[ipc_backend.validators.validate_content_section])),
                ('seo', models.JSONField(default=dict, validators=[ipc_backend.validators.validate_content_section])),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partnership Content',
                'verbose_name_plural': 'Partnership Content',
                'db_table': 'partnership_content',
            },
        ),
        migrations.CreateModel(
            name='PublicationContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(default='main', max_length=40, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hero', models.JSONField(default=dict, validators=[ipc_backend.validators.validate_content_section])),
                ('routes', models.JSONField(default=dict, validators=[ipc_backend.validators.validate_content_section])),
                ('value', models.JSONField(default=dict, validators=[ipc_backend.validators.validate_content_section])),
                ('principles', models.JSONField(default=dict, validators=[ipc_backend.validators.validate_content_section])),
                ('process', models.JSONField(default=dict, validators=[ipc_backend.validators.validate_content_section])),
                ('faq', models.JSONField(default=dict, validators=[ipc_backend.validators.validate_content_section])),
                ('final_cta', models.JSONField(default=dict, validators=[ipc_backend.validators.validate_content_section])),
                ('seo', models.JSONField(default=dict, validators=[ipc_backend.validators.validate_content_section])),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Publication Content',
                'verbose_name_plural': 'Publication Content',
                'db_table': 'publication_content',
            },
        ),
    ]
