# Generated by Django 5.2.15 on 2026-07-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_name', models.CharField(max_length=220)),
                ('event_type', models.CharField(choices=[('London Master Class', 'London Master Class'), ('Regional Club', 'Regional Club'), ('Other', 'Other')], max_length=40)),
                ('name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('organisation', models.CharField(blank=True, max_length=180)),
                ('dietary_access_needs', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
