# Generated by Django 5.2.15 on 2026-07-09 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='status',
            field=models.CharField(choices=[('registered', 'Registered'), ('waitlisted', 'Waitlisted'), ('cancelled', 'Cancelled')], default='registered', max_length=24),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(max_length=240, unique=True)),
                ('event_type', models.CharField(choices=[('london_master_class', 'London Master Class'), ('regional_club', 'Regional Club'), ('other', 'Other')], max_length=40)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=220)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['starts_at', 'title'],
                'indexes': [models.Index(fields=['event_type', 'starts_at'], name='events_even_event_t_3fa0e1_idx'), models.Index(fields=['is_published', 'starts_at'], name='events_even_is_publ_415ff6_idx'), models.Index(fields=['slug'], name='events_even_slug_30eb0f_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_at__isnull', True), ('starts_at__isnull', True), ('ends_at__gte', models.F('starts_at')), _connector='OR'), name='event_ends_at_gte_starts_at')],
            },
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='events.event'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['event', 'created_at'], name='events_even_event_i_6b3a3c_idx'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['email'], name='events_even_email_87537a_idx'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['status'], name='events_even_status_bdf692_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('event__isnull', False)), fields=('event', 'email'), name='unique_event_registration_email'),
        ),
    ]
