# Generated by Django 5.2.15 on 2026-07-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventregistration_status_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventbriteConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_token', models.TextField()),
                ('token_type', models.CharField(blank=True, max_length=40)),
                ('scope', models.TextField(blank=True)),
                ('organization_id', models.CharField(blank=True, max_length=64)),
                ('organization_name', models.CharField(blank=True, max_length=220)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='eventbrite_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='event',
            name='eventbrite_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_name',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['eventbrite_id'], name='events_even_eventbr_b0f256_idx'),
        ),
    ]
