# Generated by Django 5.2.16 on 2026-07-15 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_is_hidden_on_site'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(blank=True, max_length=40)),
                ('company', models.CharField(blank=True, max_length=180)),
                ('job_title', models.CharField(blank=True, max_length=160)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('dietary_access_needs', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EventQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=220)),
                ('help_text', models.CharField(blank=True, max_length=300)),
                ('question_type', models.CharField(choices=[('short_text', 'Short text'), ('long_text', 'Long text'), ('select', 'Select'), ('radio', 'Radio'), ('checkbox', 'Checkbox'), ('yes_no', 'Yes / No')], max_length=24)),
                ('options', models.JSONField(blank=True, default=list)),
                ('is_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistrationAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='eventregistration',
            name='unique_event_registration_email',
        ),
        migrations.AddField(
            model_name='event',
            name='max_tickets_per_registration',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_closes_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_opens_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_title',
            field=models.CharField(default='Event registration', max_length=120),
        ),
        migrations.AddField(
            model_name='event',
            name='timezone',
            field=models.CharField(default='Europe/London', max_length=64),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='access_token',
            field=models.CharField(blank=True, max_length=96, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='company',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='confirmation_email_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='confirmation_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='confirmation_email_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='contact_first_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='contact_last_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='contact_mobile',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='currency',
            field=models.CharField(default='GBP', max_length=3),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=72, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='job_title',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='marketing_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='reference',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='registered_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='ticket_name',
            field=models.CharField(default='Event registration', max_length=120),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='status',
            field=models.CharField(choices=[('registered', 'Registered'), ('confirmed', 'Confirmed'), ('attended', 'Attended'), ('waitlisted', 'Waitlisted'), ('cancelled', 'Cancelled')], default='registered', max_length=24),
        ),
        migrations.AddField(
            model_name='eventattendee',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='events.eventregistration'),
        ),
        migrations.AddField(
            model_name='eventquestion',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_questions', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventregistrationanswer',
            name='attendee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='events.eventattendee'),
        ),
        migrations.AddField(
            model_name='eventregistrationanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='events.eventquestion'),
        ),
        migrations.AddField(
            model_name='eventregistrationanswer',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='events.eventregistration'),
        ),
        migrations.AddConstraint(
            model_name='eventregistrationanswer',
            constraint=models.UniqueConstraint(fields=('registration', 'attendee', 'question'), name='unique_registration_attendee_question'),
        ),
    ]
