# Generated by Django 5.2.16 on 2026-07-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_eventattendee_eventquestion_eventregistrationanswer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='payment_provider',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='payment_reference',
            field=models.CharField(blank=True, db_index=True, max_length=160),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='payment_status',
            field=models.CharField(choices=[('not_required', 'Not required'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='not_required', max_length=20),
        ),
    ]
