# Generated by Django 5.2.16 on 2026-07-28 08:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_event_details_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='eventregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('registered_user__isnull', False), ('status__in', ['registered', 'confirmed', 'attended', 'waitlisted'])), fields=('event', 'registered_user'), name='unique_active_user_event_booking'),
        ),
    ]
