# Generated by Django 5.2.16 on 2026-07-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0002_scholarshipcontent_application_process_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipcontent',
            name='legacy_content',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
