# Generated by Django 5.2.16 on 2026-07-21 12:32

import ipc_backend.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0003_scholarshipcontent_legacy_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipcontent',
            name='audiences_intro',
            field=models.JSONField(default=dict, validators=[ipc_backend.validators.validate_content_section]),
        ),
        migrations.AddField(
            model_name='scholarshipcontent',
            name='values_intro',
            field=models.JSONField(default=dict, validators=[ipc_backend.validators.validate_content_section]),
        ),
    ]
