# Generated by Django 5.2.16 on 2026-07-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0028_bursaryapplication_bursaryapplicationstatushistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bursaryapplication',
            name='membership_reference',
            field=models.CharField(db_index=True, default='', max_length=40),
        ),
    ]
