# Generated by Django 5.2
import django.db.models.deletion
import uuid
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(
            name="ChatConversation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("access_token_hash", models.CharField(editable=False, max_length=64)),
                ("customer_name", models.CharField(max_length=160)),
                ("customer_email", models.EmailField(max_length=254)),
                ("source", models.CharField(default="general", max_length=80)),
                ("status", models.CharField(choices=[("open", "Open"), ("closed", "Closed"), ("spam", "Spam")], default="open", max_length=16)),
                ("last_message_at", models.DateTimeField(db_index=True, default=timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ("-last_message_at",)},
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sender_type", models.CharField(choices=[("customer", "Customer"), ("staff", "Staff")], max_length=16)),
                ("message", models.TextField(max_length=4000)),
                ("client_message_id", models.UUIDField(blank=True, null=True)),
                ("provider_message_id", models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ("outbound_email_id", models.CharField(blank=True, max_length=255)),
                ("email_sent_at", models.DateTimeField(blank=True, null=True)),
                ("email_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("conversation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="chat.chatconversation")),
            ],
            options={"ordering": ("created_at", "id")},
        ),
        migrations.AddIndex(model_name="chatconversation", index=models.Index(fields=["status", "last_message_at"], name="chat_conv_status_last_idx")),
        migrations.AddIndex(model_name="chatconversation", index=models.Index(fields=["customer_email"], name="chat_conv_email_idx")),
        migrations.AddIndex(model_name="chatmessage", index=models.Index(fields=["conversation", "created_at"], name="chat_msg_conv_created_idx")),
        migrations.AddConstraint(
            model_name="chatmessage",
            constraint=models.UniqueConstraint(condition=models.Q(("client_message_id__isnull", False)), fields=("conversation", "client_message_id"), name="chat_unique_client_message"),
        ),
    ]
