# Generated by Django 5.2.16 on 2026-07-21 12:26

import django.db.models.deletion
import ipc_backend.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorship', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorshipcontent',
            name='benefits',
            field=models.JSONField(default=dict, validators=[ipc_backend.validators.validate_content_section]),
        ),
        migrations.AddField(
            model_name='sponsorshipcontent',
            name='faq',
            field=models.JSONField(default=dict, validators=[ipc_backend.validators.validate_content_section]),
        ),
        migrations.AddField(
            model_name='sponsorshipcontent',
            name='final_cta',
            field=models.JSONField(default=dict, validators=[ipc_backend.validators.validate_content_section]),
        ),
        migrations.AddField(
            model_name='sponsorshipcontent',
            name='hero',
            field=models.JSONField(default=dict, validators=[ipc_backend.validators.validate_content_section]),
        ),
        migrations.AddField(
            model_name='sponsorshipcontent',
            name='impact',
            field=models.JSONField(default=dict, validators=[ipc_backend.validators.validate_content_section]),
        ),
        migrations.AddField(
            model_name='sponsorshipcontent',
            name='principles',
            field=models.JSONField(default=dict, validators=[ipc_backend.validators.validate_content_section]),
        ),
        migrations.AddField(
            model_name='sponsorshipcontent',
            name='process',
            field=models.JSONField(default=dict, validators=[ipc_backend.validators.validate_content_section]),
        ),
        migrations.AddField(
            model_name='sponsorshipcontent',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sponsorshipcontent',
            name='purpose',
            field=models.JSONField(default=dict, validators=[ipc_backend.validators.validate_content_section]),
        ),
        migrations.AddField(
            model_name='sponsorshipcontent',
            name='route_builder',
            field=models.JSONField(default=dict, validators=[ipc_backend.validators.validate_content_section]),
        ),
        migrations.AddField(
            model_name='sponsorshipcontent',
            name='seo',
            field=models.JSONField(default=dict, validators=[ipc_backend.validators.validate_content_section]),
        ),
        migrations.AddField(
            model_name='sponsorshipcontent',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=16),
        ),
        migrations.AddField(
            model_name='sponsorshipcontent',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_sponsorship_content', to=settings.AUTH_USER_MODEL),
        ),
    ]
