# Generated by Django 5.2.16 on 2026-07-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorship', '0002_sponsorshipcontent_benefits_sponsorshipcontent_faq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorshipcontent',
            name='legacy_content',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
