# Generated by Django 5.2.16 on 2026-07-21 14:29

import django.db.models.deletion
import ipc_backend.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_clubpagecontent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clubpagecontent',
            name='audiences_intro',
            field=models.JSONField(blank=True, default=dict, validators=[ipc_backend.validators.validate_content_section]),
        ),
        migrations.AddField(
            model_name='clubpagecontent',
            name='contribution',
            field=models.JSONField(blank=True, default=dict, validators=[ipc_backend.validators.validate_content_section]),
        ),
        migrations.AddField(
            model_name='clubpagecontent',
            name='faq',
            field=models.JSONField(blank=True, default=dict, validators=[ipc_backend.validators.validate_content_section]),
        ),
        migrations.AddField(
            model_name='clubpagecontent',
            name='final_cta',
            field=models.JSONField(blank=True, default=dict, validators=[ipc_backend.validators.validate_content_section]),
        ),
        migrations.AddField(
            model_name='clubpagecontent',
            name='hero',
            field=models.JSONField(blank=True, default=dict, validators=[ipc_backend.validators.validate_content_section]),
        ),
        migrations.AddField(
            model_name='clubpagecontent',
            name='legacy_content',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='clubpagecontent',
            name='locations_intro',
            field=models.JSONField(blank=True, default=dict, validators=[ipc_backend.validators.validate_content_section]),
        ),
        migrations.AddField(
            model_name='clubpagecontent',
            name='partners',
            field=models.JSONField(blank=True, default=dict, validators=[ipc_backend.validators.validate_content_section]),
        ),
        migrations.AddField(
            model_name='clubpagecontent',
            name='principles',
            field=models.JSONField(blank=True, default=dict, validators=[ipc_backend.validators.validate_content_section]),
        ),
        migrations.AddField(
            model_name='clubpagecontent',
            name='programme_intro',
            field=models.JSONField(blank=True, default=dict, validators=[ipc_backend.validators.validate_content_section]),
        ),
        migrations.AddField(
            model_name='clubpagecontent',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubpagecontent',
            name='purpose',
            field=models.JSONField(blank=True, default=dict, validators=[ipc_backend.validators.validate_content_section]),
        ),
        migrations.AddField(
            model_name='clubpagecontent',
            name='seo',
            field=models.JSONField(blank=True, default=dict, validators=[ipc_backend.validators.validate_content_section]),
        ),
        migrations.AddField(
            model_name='clubpagecontent',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=20),
        ),
        migrations.AddField(
            model_name='clubpagecontent',
            name='upcoming',
            field=models.JSONField(blank=True, default=dict, validators=[ipc_backend.validators.validate_content_section]),
        ),
        migrations.AddField(
            model_name='clubpagecontent',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_club_content', to=settings.AUTH_USER_MODEL),
        ),
    ]
