-- Generated from the connected PostgreSQL database.
-- Table: "public"."accounts_adminprofile"

CREATE TABLE "public"."accounts_adminprofile" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "role" character varying(24) NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "user_id" integer NOT NULL,
    CONSTRAINT "accounts_adminprofile_pkey" PRIMARY KEY (id),
    CONSTRAINT "accounts_adminprofile_user_id_key" UNIQUE (user_id),
    CONSTRAINT "accounts_adminprofile_user_id_bb9bff2e_fk_auth_user_id" FOREIGN KEY (user_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED
);

-- Indexes
CREATE INDEX accounts_ad_role_6e9707_idx ON public.accounts_adminprofile USING btree (role);
