-- Generated from the connected PostgreSQL database.
-- Table: "public"."applications_applicationevidence"

CREATE TABLE "public"."applications_applicationevidence" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "evidence_type" character varying(24) NOT NULL,
    "file" character varying(100) NOT NULL,
    "original_name" character varying(255) NOT NULL,
    "uploaded_at" timestamp with time zone NOT NULL,
    "application_id" bigint NOT NULL,
    "content_type" character varying(120) NOT NULL,
    "file_size" integer NOT NULL,
    "uploaded_by_id" integer,
    "updated_at" timestamp with time zone NOT NULL,
    CONSTRAINT "applications_applicationevidence_pkey" PRIMARY KEY (id),
    CONSTRAINT "applications_applicationevidence_file_size_check" CHECK (file_size >= 0),
    CONSTRAINT "applications_applica_application_id_96cd7cba_fk_applicati" FOREIGN KEY (application_id) REFERENCES applications_application(id) DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT "applications_applica_uploaded_by_id_df082b9d_fk_auth_user" FOREIGN KEY (uploaded_by_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED
);

-- Indexes
CREATE INDEX application_applica_195612_idx ON public.applications_applicationevidence USING btree (application_id, evidence_type);
CREATE INDEX application_uploade_63ce82_idx ON public.applications_applicationevidence USING btree (uploaded_at);
CREATE INDEX applications_applicationevidence_application_id_96cd7cba ON public.applications_applicationevidence USING btree (application_id);
CREATE INDEX applications_applicationevidence_uploaded_by_id_df082b9d ON public.applications_applicationevidence USING btree (uploaded_by_id);
