-- Generated from the connected PostgreSQL database.
-- Table: "public"."applications_formdefinition"

CREATE TABLE "public"."applications_formdefinition" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "code" character varying(32) NOT NULL,
    "name" character varying(160) NOT NULL,
    "version" smallint NOT NULL,
    "validation_schema" jsonb NOT NULL,
    "is_active" boolean NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    CONSTRAINT "applications_formdefinition_pkey" PRIMARY KEY (id),
    CONSTRAINT "uniq_form_code_version" UNIQUE (code, version),
    CONSTRAINT "applications_formdefinition_version_check" CHECK (version >= 0)
);

-- Indexes
CREATE INDEX form_code_active_idx ON public.applications_formdefinition USING btree (code, is_active);
