-- Generated from the connected PostgreSQL database.
-- Table: "public"."applications_applicationreference"

CREATE TABLE "public"."applications_applicationreference" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "name" character varying(160) NOT NULL,
    "email" character varying(254) NOT NULL,
    "organisation" character varying(180) NOT NULL,
    "relationship" character varying(160) NOT NULL,
    "notes" text NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "application_id" bigint NOT NULL,
    CONSTRAINT "applications_applicationreference_pkey" PRIMARY KEY (id),
    CONSTRAINT "applications_applica_application_id_e4ab657b_fk_applicati" FOREIGN KEY (application_id) REFERENCES applications_application(id) DEFERRABLE INITIALLY DEFERRED
);

-- Indexes
CREATE INDEX application_applica_58c801_idx ON public.applications_applicationreference USING btree (application_id);
CREATE INDEX applications_applicationreference_application_id_e4ab657b ON public.applications_applicationreference USING btree (application_id);
