-- Generated from the connected PostgreSQL database.
-- Table: "public"."applications_applicationstatushistory"

CREATE TABLE "public"."applications_applicationstatushistory" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "from_status" character varying(32),
    "to_status" character varying(32) NOT NULL,
    "note" text NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "application_id" bigint NOT NULL,
    "changed_by_id" integer,
    CONSTRAINT "applications_applicationstatushistory_pkey" PRIMARY KEY (id),
    CONSTRAINT "applications_applica_application_id_f1136399_fk_applicati" FOREIGN KEY (application_id) REFERENCES applications_application(id) DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT "applications_applica_changed_by_id_312a24d5_fk_auth_user" FOREIGN KEY (changed_by_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED
);

-- Indexes
CREATE INDEX application_applica_1aaa33_idx ON public.applications_applicationstatushistory USING btree (application_id, created_at);
CREATE INDEX application_to_stat_8c9938_idx ON public.applications_applicationstatushistory USING btree (to_status, created_at);
CREATE INDEX applications_applicationstatushistory_application_id_f1136399 ON public.applications_applicationstatushistory USING btree (application_id);
CREATE INDEX applications_applicationstatushistory_changed_by_id_312a24d5 ON public.applications_applicationstatushistory USING btree (changed_by_id);
