-- Generated from the connected PostgreSQL database.
-- Table: "public"."applications_application"

CREATE TABLE "public"."applications_application" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "status" character varying(32) NOT NULL,
    "first_name" character varying(120) NOT NULL,
    "last_name" character varying(120) NOT NULL,
    "email" character varying(254) NOT NULL,
    "phone" character varying(80) NOT NULL,
    "country" character varying(120) NOT NULL,
    "organisation" character varying(180) NOT NULL,
    "code_of_conduct_consent" boolean NOT NULL,
    "reviewed_at" timestamp with time zone,
    "reviewed_by_id" integer,
    "application_reference" character varying(32) NOT NULL,
    "membership_grade_id" bigint NOT NULL,
    "privacy_consent" boolean NOT NULL,
    "contact_preference" character varying(16) NOT NULL,
    "form_definition_id" bigint NOT NULL,
    "form_version" smallint NOT NULL,
    "grade_specific_data" jsonb NOT NULL,
    "submitted_at" timestamp with time zone NOT NULL,
    CONSTRAINT "applications_membershipapplication_pkey" PRIMARY KEY (id),
    CONSTRAINT "applications_membershipapplication_application_reference_key" UNIQUE (application_reference),
    CONSTRAINT "applications_application_form_version_check" CHECK (form_version >= 0),
    CONSTRAINT "applications_applica_form_definition_id_1f78bd05_fk_applicati" FOREIGN KEY (form_definition_id) REFERENCES applications_formdefinition(id) DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT "applications_applica_membership_grade_id_762c8bab_fk_membershi" FOREIGN KEY (membership_grade_id) REFERENCES memberships_membershipgrade(id) DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT "applications_members_reviewed_by_id_4e18cbee_fk_auth_user" FOREIGN KEY (reviewed_by_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED
);

-- Indexes
CREATE INDEX app_email_idx ON public.applications_application USING btree (email);
CREATE INDEX app_form_version_idx ON public.applications_application USING btree (form_definition_id, form_version);
CREATE INDEX app_reviewer_idx ON public.applications_application USING btree (reviewed_by_id);
CREATE INDEX app_status_grade_created_idx ON public.applications_application USING btree (status, membership_grade_id, created_at);
CREATE INDEX app_submitted_idx ON public.applications_application USING btree (submitted_at);
CREATE INDEX applications_application_form_definition_id_1f78bd05 ON public.applications_application USING btree (form_definition_id);
CREATE INDEX applications_membershipa_application_reference_57eb1064_like ON public.applications_application USING btree (application_reference varchar_pattern_ops);
CREATE INDEX applications_membershipapplication_membership_grade_id_2df4b417 ON public.applications_application USING btree (membership_grade_id);
CREATE INDEX applications_membershipapplication_reviewed_by_id_4e18cbee ON public.applications_application USING btree (reviewed_by_id);
