-- Generated from the connected PostgreSQL database.
-- Table: "public"."applications_reviewernote"

CREATE TABLE "public"."applications_reviewernote" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "note" text NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "application_id" bigint NOT NULL,
    "author_id" integer,
    "is_internal" boolean NOT NULL,
    CONSTRAINT "applications_reviewernote_pkey" PRIMARY KEY (id),
    CONSTRAINT "applications_reviewe_application_id_74ec5779_fk_applicati" FOREIGN KEY (application_id) REFERENCES applications_application(id) DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT "applications_reviewernote_author_id_83bfb422_fk_auth_user_id" FOREIGN KEY (author_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED
);

-- Indexes
CREATE INDEX application_applica_31b183_idx ON public.applications_reviewernote USING btree (application_id, created_at);
CREATE INDEX applications_reviewernote_application_id_74ec5779 ON public.applications_reviewernote USING btree (application_id);
CREATE INDEX applications_reviewernote_author_id_83bfb422 ON public.applications_reviewernote USING btree (author_id);
