-- Generated from the connected PostgreSQL database.
-- Table: "public"."auth_group"

CREATE TABLE "public"."auth_group" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "name" character varying(150) NOT NULL,
    CONSTRAINT "auth_group_pkey" PRIMARY KEY (id),
    CONSTRAINT "auth_group_name_key" UNIQUE (name)
);

-- Indexes
CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);
