-- Generated from the connected PostgreSQL database.
-- Table: "public"."auth_permission"

CREATE TABLE "public"."auth_permission" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "name" character varying(255) NOT NULL,
    "content_type_id" integer NOT NULL,
    "codename" character varying(100) NOT NULL,
    CONSTRAINT "auth_permission_pkey" PRIMARY KEY (id),
    CONSTRAINT "auth_permission_content_type_id_codename_01ab375a_uniq" UNIQUE (content_type_id, codename),
    CONSTRAINT "auth_permission_content_type_id_2f476e4b_fk_django_co" FOREIGN KEY (content_type_id) REFERENCES django_content_type(id) DEFERRABLE INITIALLY DEFERRED
);

-- Indexes
CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);
