-- Generated from the connected PostgreSQL database.
-- Table: "public"."auth_user"

CREATE TABLE "public"."auth_user" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "password" character varying(128) NOT NULL,
    "last_login" timestamp with time zone,
    "is_superuser" boolean NOT NULL,
    "username" character varying(150) NOT NULL,
    "first_name" character varying(150) NOT NULL,
    "last_name" character varying(150) NOT NULL,
    "email" character varying(254) NOT NULL,
    "is_staff" boolean NOT NULL,
    "is_active" boolean NOT NULL,
    "date_joined" timestamp with time zone NOT NULL,
    CONSTRAINT "auth_user_pkey" PRIMARY KEY (id),
    CONSTRAINT "auth_user_username_key" UNIQUE (username)
);

-- Indexes
CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);
