-- Generated from the connected PostgreSQL database.
-- Table: "public"."awards_awardprogramme"

CREATE TABLE "public"."awards_awardprogramme" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "title" character varying(180) NOT NULL,
    "slug" character varying(200) NOT NULL,
    "description" text NOT NULL,
    "category" character varying(32) NOT NULL,
    "is_active" boolean NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    CONSTRAINT "awards_awardprogramme_pkey" PRIMARY KEY (id),
    CONSTRAINT "awards_awardprogramme_slug_key" UNIQUE (slug)
);

-- Indexes
CREATE INDEX awards_awar_categor_4f1292_idx ON public.awards_awardprogramme USING btree (category, is_active);
CREATE INDEX awards_awar_slug_1d6b47_idx ON public.awards_awardprogramme USING btree (slug);
CREATE INDEX awards_awardprogramme_slug_6d113d8b_like ON public.awards_awardprogramme USING btree (slug varchar_pattern_ops);
