-- Generated from the connected PostgreSQL database.
-- Table: "public"."awards_awardsinterest"

CREATE TABLE "public"."awards_awardsinterest" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "name" character varying(160) NOT NULL,
    "email" character varying(254) NOT NULL,
    "interest_type" character varying(24) NOT NULL,
    "message" text NOT NULL,
    "status" character varying(24) NOT NULL,
    "programme_id" bigint,
    CONSTRAINT "awards_awardsinterest_pkey" PRIMARY KEY (id),
    CONSTRAINT "awards_awardsinteres_programme_id_f7acb404_fk_awards_aw" FOREIGN KEY (programme_id) REFERENCES awards_awardprogramme(id) DEFERRABLE INITIALLY DEFERRED
);

-- Indexes
CREATE INDEX awards_awar_email_c71480_idx ON public.awards_awardsinterest USING btree (email);
CREATE INDEX awards_awar_interes_419ad9_idx ON public.awards_awardsinterest USING btree (interest_type, created_at);
CREATE INDEX awards_awar_status_7e515e_idx ON public.awards_awardsinterest USING btree (status);
CREATE INDEX awards_awardsinterest_programme_id_f7acb404 ON public.awards_awardsinterest USING btree (programme_id);
