-- Generated from the connected PostgreSQL database.
-- Table: "public"."contact_contactsubmission"

CREATE TABLE "public"."contact_contactsubmission" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "name" character varying(160) NOT NULL,
    "email" character varying(254) NOT NULL,
    "category" character varying(120) NOT NULL,
    "message" text NOT NULL,
    "handled" boolean NOT NULL,
    "handled_at" timestamp with time zone,
    "handled_by_id" integer,
    "status" character varying(24) NOT NULL,
    CONSTRAINT "contact_contactsubmission_pkey" PRIMARY KEY (id),
    CONSTRAINT "contact_contactsubmi_handled_by_id_f17f7a60_fk_auth_user" FOREIGN KEY (handled_by_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED
);

-- Indexes
CREATE INDEX contact_con_categor_4d2022_idx ON public.contact_contactsubmission USING btree (category);
CREATE INDEX contact_con_email_394734_idx ON public.contact_contactsubmission USING btree (email);
CREATE INDEX contact_con_status_57081e_idx ON public.contact_contactsubmission USING btree (status, created_at);
CREATE INDEX contact_contactsubmission_handled_by_id_f17f7a60 ON public.contact_contactsubmission USING btree (handled_by_id);
