-- Generated from the connected PostgreSQL database.
-- Table: "public"."django_migrations"

CREATE TABLE "public"."django_migrations" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "app" character varying(255) NOT NULL,
    "name" character varying(255) NOT NULL,
    "applied" timestamp with time zone NOT NULL,
    CONSTRAINT "django_migrations_pkey" PRIMARY KEY (id)
);
