-- Generated from the connected PostgreSQL database.
-- Table: "public"."django_content_type"

CREATE TABLE "public"."django_content_type" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "app_label" character varying(100) NOT NULL,
    "model" character varying(100) NOT NULL,
    CONSTRAINT "django_content_type_pkey" PRIMARY KEY (id),
    CONSTRAINT "django_content_type_app_label_model_76bd3d3b_uniq" UNIQUE (app_label, model)
);
