-- Generated from the connected PostgreSQL database.
-- Table: "public"."events_eventregistration"

CREATE TABLE "public"."events_eventregistration" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "event_name" character varying(220) NOT NULL,
    "event_type" character varying(40) NOT NULL,
    "name" character varying(160) NOT NULL,
    "email" character varying(254) NOT NULL,
    "organisation" character varying(180) NOT NULL,
    "dietary_access_needs" text NOT NULL,
    "status" character varying(24) NOT NULL,
    "event_id" bigint,
    CONSTRAINT "events_eventregistration_pkey" PRIMARY KEY (id),
    CONSTRAINT "events_eventregistration_event_id_9b88b424_fk_events_event_id" FOREIGN KEY (event_id) REFERENCES events_event(id) DEFERRABLE INITIALLY DEFERRED
);

-- Indexes
CREATE INDEX events_even_email_87537a_idx ON public.events_eventregistration USING btree (email);
CREATE INDEX events_even_event_i_6b3a3c_idx ON public.events_eventregistration USING btree (event_id, created_at);
CREATE INDEX events_even_status_bdf692_idx ON public.events_eventregistration USING btree (status);
CREATE INDEX events_eventregistration_event_id_9b88b424 ON public.events_eventregistration USING btree (event_id);
CREATE UNIQUE INDEX unique_event_registration_email ON public.events_eventregistration USING btree (event_id, email) WHERE (event_id IS NOT NULL);
