-- Generated from the connected PostgreSQL database.
-- Table: "public"."events_eventbriteconnection"

CREATE TABLE "public"."events_eventbriteconnection" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "access_token" text NOT NULL,
    "token_type" character varying(40) NOT NULL,
    "scope" text NOT NULL,
    "organization_id" character varying(64) NOT NULL,
    "organization_name" character varying(220) NOT NULL,
    "last_synced_at" timestamp with time zone,
    CONSTRAINT "events_eventbriteconnection_pkey" PRIMARY KEY (id)
);
