-- Generated from the connected PostgreSQL database.
-- Table: "public"."events_event"

CREATE TABLE "public"."events_event" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "title" character varying(220) NOT NULL,
    "slug" character varying(240) NOT NULL,
    "event_type" character varying(40) NOT NULL,
    "description" text NOT NULL,
    "location" character varying(220) NOT NULL,
    "region" character varying(120) NOT NULL,
    "starts_at" timestamp with time zone,
    "ends_at" timestamp with time zone,
    "capacity" integer,
    "is_published" boolean NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "eventbrite_id" character varying(64),
    "eventbrite_url" character varying(500) NOT NULL,
    "image_url" character varying(500) NOT NULL,
    "venue_name" character varying(220) NOT NULL,
    "status" character varying(32) NOT NULL,
    "is_online_event" boolean NOT NULL,
    "is_featured" boolean NOT NULL,
    CONSTRAINT "events_event_pkey" PRIMARY KEY (id),
    CONSTRAINT "events_event_eventbrite_id_key" UNIQUE (eventbrite_id),
    CONSTRAINT "events_event_slug_key" UNIQUE (slug),
    CONSTRAINT "event_ends_at_gte_starts_at" CHECK (ends_at IS NULL OR starts_at IS NULL OR ends_at >= starts_at),
    CONSTRAINT "events_event_capacity_check" CHECK (capacity >= 0)
);

-- Indexes
CREATE INDEX events_even_event_t_3fa0e1_idx ON public.events_event USING btree (event_type, starts_at);
CREATE INDEX events_even_eventbr_b0f256_idx ON public.events_event USING btree (eventbrite_id);
CREATE INDEX events_even_is_publ_415ff6_idx ON public.events_event USING btree (is_published, starts_at);
CREATE INDEX events_even_slug_30eb0f_idx ON public.events_event USING btree (slug);
CREATE INDEX events_event_eventbrite_id_d1080da5_like ON public.events_event USING btree (eventbrite_id varchar_pattern_ops);
CREATE INDEX events_event_slug_b44b2c04_like ON public.events_event USING btree (slug varchar_pattern_ops);
