-- Generated from the connected PostgreSQL database.
-- Table: "public"."media_library_mediarendition"

CREATE TABLE "public"."media_library_mediarendition" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "format" character varying(16) NOT NULL,
    "width" integer NOT NULL,
    "height" integer NOT NULL,
    "file" character varying(100) NOT NULL,
    "file_size" integer NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "asset_id" bigint NOT NULL,
    CONSTRAINT "media_library_mediarendition_pkey" PRIMARY KEY (id),
    CONSTRAINT "unique_media_rendition_size_format" UNIQUE (asset_id, format, width, height),
    CONSTRAINT "media_library_mediarendition_file_size_check" CHECK (file_size >= 0),
    CONSTRAINT "media_library_mediarendition_height_check" CHECK (height >= 0),
    CONSTRAINT "media_library_mediarendition_width_check" CHECK (width >= 0),
    CONSTRAINT "media_library_mediar_asset_id_de405e5f_fk_media_lib" FOREIGN KEY (asset_id) REFERENCES media_library_mediaasset(id) DEFERRABLE INITIALLY DEFERRED
);

-- Indexes
CREATE INDEX media_libra_asset_i_d16ad7_idx ON public.media_library_mediarendition USING btree (asset_id, format);
CREATE INDEX media_libra_width_e29043_idx ON public.media_library_mediarendition USING btree (width, height);
CREATE INDEX media_library_mediarendition_asset_id_de405e5f ON public.media_library_mediarendition USING btree (asset_id);
