-- Generated from the connected PostgreSQL database.
-- Table: "public"."media_library_mediaasset"

CREATE TABLE "public"."media_library_mediaasset" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "title" character varying(180) NOT NULL,
    "alt_text" character varying(240) NOT NULL,
    "image" character varying(100) NOT NULL,
    "width" integer NOT NULL,
    "height" integer NOT NULL,
    "webp_image" character varying(100) NOT NULL,
    "avif_image" character varying(100) NOT NULL,
    "is_brand_asset" boolean NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    CONSTRAINT "media_library_mediaasset_pkey" PRIMARY KEY (id),
    CONSTRAINT "media_library_mediaasset_height_check" CHECK (height >= 0),
    CONSTRAINT "media_library_mediaasset_width_check" CHECK (width >= 0)
);

-- Indexes
CREATE INDEX media_libra_created_2f9af3_idx ON public.media_library_mediaasset USING btree (created_at);
CREATE INDEX media_libra_is_bran_09dff5_idx ON public.media_library_mediaasset USING btree (is_brand_asset);
