-- Generated from the connected PostgreSQL database.
-- Table: "public"."memberships_membershipgraderequirement"

CREATE TABLE "public"."memberships_membershipgraderequirement" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "requirement_type" character varying(24) NOT NULL,
    "title" character varying(160) NOT NULL,
    "description" text NOT NULL,
    "is_required" boolean NOT NULL,
    "display_order" smallint NOT NULL,
    "grade_id" bigint NOT NULL,
    CONSTRAINT "memberships_membershipgraderequirement_pkey" PRIMARY KEY (id),
    CONSTRAINT "grade_requirement_display_order_gte_0" CHECK (display_order >= 0),
    CONSTRAINT "memberships_membershipgraderequirement_display_order_check" CHECK (display_order >= 0),
    CONSTRAINT "memberships_membersh_grade_id_96c77cd6_fk_membershi" FOREIGN KEY (grade_id) REFERENCES memberships_membershipgrade(id) DEFERRABLE INITIALLY DEFERRED
);

-- Indexes
CREATE INDEX memberships_grade_i_d2011a_idx ON public.memberships_membershipgraderequirement USING btree (grade_id, requirement_type);
CREATE INDEX memberships_grade_i_ebeac9_idx ON public.memberships_membershipgraderequirement USING btree (grade_id, display_order);
CREATE INDEX memberships_membershipgraderequirement_grade_id_96c77cd6 ON public.memberships_membershipgraderequirement USING btree (grade_id);
