-- Generated from the connected PostgreSQL database.
-- Table: "public"."memberships_membershipgrade"

CREATE TABLE "public"."memberships_membershipgrade" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "code" character varying(16) NOT NULL,
    "title" character varying(160) NOT NULL,
    "description" text NOT NULL,
    "evidence_requirements" text NOT NULL,
    "cpd_requirements" text NOT NULL,
    "is_active" boolean NOT NULL,
    "display_order" smallint NOT NULL,
    "application_pathway" text NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "professional_recognition" text NOT NULL,
    "short_title" character varying(80) NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "slug" character varying(80) NOT NULL,
    "image_url" character varying(255) NOT NULL,
    "post_nominal" character varying(32) NOT NULL,
    "pathway_title" character varying(255) NOT NULL,
    "pathway_description" text NOT NULL,
    CONSTRAINT "memberships_membershipgrade_pkey" PRIMARY KEY (id),
    CONSTRAINT "memberships_membershipgrade_code_key" UNIQUE (code),
    CONSTRAINT "memberships_membershipgrade_slug_key" UNIQUE (slug),
    CONSTRAINT "membership_grade_display_order_gte_0" CHECK (display_order >= 0),
    CONSTRAINT "memberships_membershipgrade_display_order_check" CHECK (display_order >= 0)
);

-- Indexes
CREATE INDEX memberships_code_bdf7d5_idx ON public.memberships_membershipgrade USING btree (code);
CREATE INDEX memberships_is_acti_ebfe90_idx ON public.memberships_membershipgrade USING btree (is_active, display_order);
CREATE INDEX memberships_membershipgrade_code_6c8ff678_like ON public.memberships_membershipgrade USING btree (code varchar_pattern_ops);
CREATE INDEX memberships_membershipgrade_slug_730c8cca_like ON public.memberships_membershipgrade USING btree (slug varchar_pattern_ops);
