-- Generated from the connected PostgreSQL database.
-- Table: "public"."memberships_membershipgradebenefit"

CREATE TABLE "public"."memberships_membershipgradebenefit" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "title" character varying(160) NOT NULL,
    "description" text NOT NULL,
    "display_order" smallint NOT NULL,
    "is_active" boolean NOT NULL,
    "grade_id" bigint NOT NULL,
    CONSTRAINT "memberships_membershipgradebenefit_pkey" PRIMARY KEY (id),
    CONSTRAINT "unique_grade_benefit_order" UNIQUE (grade_id, display_order),
    CONSTRAINT "grade_benefit_display_order_gte_0" CHECK (display_order >= 0),
    CONSTRAINT "memberships_membershipgradebenefit_display_order_check" CHECK (display_order >= 0),
    CONSTRAINT "memberships_membersh_grade_id_5fe81d07_fk_membershi" FOREIGN KEY (grade_id) REFERENCES memberships_membershipgrade(id) DEFERRABLE INITIALLY DEFERRED
);

-- Indexes
CREATE INDEX memberships_grade_i_b99f7b_idx ON public.memberships_membershipgradebenefit USING btree (grade_id, display_order);
CREATE INDEX memberships_membershipgradebenefit_grade_id_5fe81d07 ON public.memberships_membershipgradebenefit USING btree (grade_id);
