-- Generated from the connected PostgreSQL database.
-- Table: "public"."newsletter_newslettersignup"

CREATE TABLE "public"."newsletter_newslettersignup" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "email" character varying(254) NOT NULL,
    "name" character varying(160) NOT NULL,
    "consent" boolean NOT NULL,
    "is_active" boolean NOT NULL,
    "source" character varying(120) NOT NULL,
    "unsubscribed_at" timestamp with time zone,
    CONSTRAINT "newsletter_newslettersignup_pkey" PRIMARY KEY (id),
    CONSTRAINT "newsletter_newslettersignup_email_key" UNIQUE (email)
);

-- Indexes
CREATE INDEX newsletter__email_dcf2d4_idx ON public.newsletter_newslettersignup USING btree (email);
CREATE INDEX newsletter__is_acti_003fbe_idx ON public.newsletter_newslettersignup USING btree (is_active, created_at);
CREATE INDEX newsletter_newslettersignup_email_2546d0e4_like ON public.newsletter_newslettersignup USING btree (email varchar_pattern_ops);
