# Generated by Django 5.2.15 on 2026-07-09 08:34

import ipc_backend.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=180)),
                ('alt_text', models.CharField(max_length=240)),
                ('image', models.ImageField(upload_to=ipc_backend.validators.media_upload_to, validators=[ipc_backend.validators.validate_image])),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('webp_image', models.ImageField(blank=True, upload_to=ipc_backend.validators.media_upload_to)),
                ('avif_image', models.ImageField(blank=True, upload_to=ipc_backend.validators.media_upload_to)),
                ('is_brand_asset', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
