# Generated by Django 5.2.15 on 2026-07-09 11:27

import django.db.models.deletion
import ipc_backend.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaRendition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('original', 'Original'), ('webp', 'WebP'), ('avif', 'AVIF')], max_length=16)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('file', models.ImageField(upload_to=ipc_backend.validators.media_upload_to, validators=[ipc_backend.validators.validate_image])),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['asset', 'width', 'format'],
            },
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['is_brand_asset'], name='media_libra_is_bran_09dff5_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['created_at'], name='media_libra_created_2f9af3_idx'),
        ),
        migrations.AddField(
            model_name='mediarendition',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renditions', to='media_library.mediaasset'),
        ),
        migrations.AddIndex(
            model_name='mediarendition',
            index=models.Index(fields=['asset', 'format'], name='media_libra_asset_i_d16ad7_idx'),
        ),
        migrations.AddIndex(
            model_name='mediarendition',
            index=models.Index(fields=['width', 'height'], name='media_libra_width_e29043_idx'),
        ),
        migrations.AddConstraint(
            model_name='mediarendition',
            constraint=models.UniqueConstraint(fields=('asset', 'format', 'width', 'height'), name='unique_media_rendition_size_format'),
        ),
    ]
