# Generated by Django 5.2.15 on 2026-07-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('AffIPC', 'Affiliate Member / AffIPC'), ('MIPC', 'Professional Member / MIPC'), ('AFIPC_L3', 'Associate Fellow Level 3 / AFIPC L3'), ('AFIPC_L4', 'Associate Fellow Level 4 / AFIPC L4'), ('FIPC', 'Fellow / FIPC')], max_length=16, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('evidence_requirements', models.TextField(blank=True)),
                ('cpd_requirements', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'title'],
            },
        ),
    ]
