# Generated by Django 5.2.15 on 2026-07-09 11:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipGradeBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['grade__display_order', 'display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='MembershipGradeRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_type', models.CharField(choices=[('evidence', 'Evidence'), ('cpd', 'CPD'), ('work', 'Work evidence'), ('references', 'References'), ('statement', 'Professional statement'), ('other', 'Other')], max_length=24)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('is_required', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['grade__display_order', 'display_order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='membershipgrade',
            name='application_pathway',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='membershipgrade',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='membershipgrade',
            name='professional_recognition',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='membershipgrade',
            name='short_title',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='membershipgrade',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='membershipgrade',
            index=models.Index(fields=['code'], name='memberships_code_bdf7d5_idx'),
        ),
        migrations.AddIndex(
            model_name='membershipgrade',
            index=models.Index(fields=['is_active', 'display_order'], name='memberships_is_acti_ebfe90_idx'),
        ),
        migrations.AddConstraint(
            model_name='membershipgrade',
            constraint=models.CheckConstraint(condition=models.Q(('display_order__gte', 0)), name='membership_grade_display_order_gte_0'),
        ),
        migrations.AddField(
            model_name='membershipgradebenefit',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='memberships.membershipgrade'),
        ),
        migrations.AddField(
            model_name='membershipgraderequirement',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='memberships.membershipgrade'),
        ),
        migrations.AddIndex(
            model_name='membershipgradebenefit',
            index=models.Index(fields=['grade', 'display_order'], name='memberships_grade_i_b99f7b_idx'),
        ),
        migrations.AddConstraint(
            model_name='membershipgradebenefit',
            constraint=models.UniqueConstraint(fields=('grade', 'display_order'), name='unique_grade_benefit_order'),
        ),
        migrations.AddConstraint(
            model_name='membershipgradebenefit',
            constraint=models.CheckConstraint(condition=models.Q(('display_order__gte', 0)), name='grade_benefit_display_order_gte_0'),
        ),
        migrations.AddIndex(
            model_name='membershipgraderequirement',
            index=models.Index(fields=['grade', 'requirement_type'], name='memberships_grade_i_d2011a_idx'),
        ),
        migrations.AddIndex(
            model_name='membershipgraderequirement',
            index=models.Index(fields=['grade', 'display_order'], name='memberships_grade_i_ebeac9_idx'),
        ),
        migrations.AddConstraint(
            model_name='membershipgraderequirement',
            constraint=models.CheckConstraint(condition=models.Q(('display_order__gte', 0)), name='grade_requirement_display_order_gte_0'),
        ),
    ]
