import os
import sys
from pathlib import Path

BACKEND_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BACKEND_DIR))
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "ipc_backend.settings")

import django

django.setup()

from django.db import connection


SCHEMA = "public"
OUTPUT_DIR = BACKEND_DIR / "sql"


def quote(identifier: str) -> str:
    return connection.ops.quote_name(identifier)


def get_tables(cursor) -> list[str]:
    cursor.execute(
        """
        SELECT table_name
        FROM information_schema.tables
        WHERE table_schema = %s AND table_type = 'BASE TABLE'
        ORDER BY table_name
        """,
        [SCHEMA],
    )
    return [row[0] for row in cursor.fetchall()]


def get_table_oid(cursor, table: str) -> int:
    cursor.execute(
        """
        SELECT c.oid
        FROM pg_catalog.pg_class c
        JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = %s AND c.relname = %s AND c.relkind = 'r'
        """,
        [SCHEMA, table],
    )
    return cursor.fetchone()[0]


def get_columns(cursor, table_oid: int):
    cursor.execute(
        """
        SELECT
            a.attname,
            pg_catalog.format_type(a.atttypid, a.atttypmod),
            a.attnotnull,
            pg_catalog.pg_get_expr(d.adbin, d.adrelid),
            a.attidentity,
            a.attgenerated
        FROM pg_catalog.pg_attribute a
        LEFT JOIN pg_catalog.pg_attrdef d
            ON d.adrelid = a.attrelid AND d.adnum = a.attnum
        WHERE a.attrelid = %s
          AND a.attnum > 0
          AND NOT a.attisdropped
        ORDER BY a.attnum
        """,
        [table_oid],
    )
    return cursor.fetchall()


def get_constraints(cursor, table_oid: int):
    cursor.execute(
        """
        SELECT conname, contype, pg_catalog.pg_get_constraintdef(oid, true)
        FROM pg_catalog.pg_constraint
        WHERE conrelid = %s
          AND contype <> 'n'
        ORDER BY CASE contype
            WHEN 'p' THEN 1
            WHEN 'u' THEN 2
            WHEN 'c' THEN 3
            WHEN 'f' THEN 4
            ELSE 5
        END, conname
        """,
        [table_oid],
    )
    return cursor.fetchall()


def get_indexes(cursor, table_oid: int):
    cursor.execute(
        """
        SELECT pg_catalog.pg_get_indexdef(i.indexrelid)
        FROM pg_catalog.pg_index i
        LEFT JOIN pg_catalog.pg_constraint c ON c.conindid = i.indexrelid
        WHERE i.indrelid = %s
          AND c.oid IS NULL
        ORDER BY i.indexrelid::regclass::text
        """,
        [table_oid],
    )
    return [row[0] for row in cursor.fetchall()]


def get_dependencies(cursor, tables: list[str]) -> dict[str, set[str]]:
    cursor.execute(
        """
        SELECT source.relname, target.relname
        FROM pg_catalog.pg_constraint constraint_record
        JOIN pg_catalog.pg_class source ON source.oid = constraint_record.conrelid
        JOIN pg_catalog.pg_namespace source_namespace ON source_namespace.oid = source.relnamespace
        JOIN pg_catalog.pg_class target ON target.oid = constraint_record.confrelid
        JOIN pg_catalog.pg_namespace target_namespace ON target_namespace.oid = target.relnamespace
        WHERE constraint_record.contype = 'f'
          AND source_namespace.nspname = %s
          AND target_namespace.nspname = %s
        """,
        [SCHEMA, SCHEMA],
    )
    known = set(tables)
    dependencies = {table: set() for table in tables}
    for source, target in cursor.fetchall():
        if source in known and target in known and source != target:
            dependencies[source].add(target)
    return dependencies


def topological_order(dependencies: dict[str, set[str]]) -> list[str]:
    remaining = {table: set(values) for table, values in dependencies.items()}
    ordered: list[str] = []
    while remaining:
        ready = sorted(table for table, values in remaining.items() if not values)
        if not ready:
            ordered.extend(sorted(remaining))
            break
        ordered.extend(ready)
        for table in ready:
            remaining.pop(table)
        for values in remaining.values():
            values.difference_update(ready)
    return ordered


def render_column(column) -> str:
    name, data_type, not_null, default, identity, generated = column
    definition = f"    {quote(name)} {data_type}"
    if identity == "a":
        definition += " GENERATED ALWAYS AS IDENTITY"
    elif identity == "d":
        definition += " GENERATED BY DEFAULT AS IDENTITY"
    elif generated == "s":
        definition += f" GENERATED ALWAYS AS ({default}) STORED"
        default = None
    elif default and default.startswith("nextval("):
        if data_type == "bigint":
            definition = f"    {quote(name)} bigserial"
        elif data_type == "integer":
            definition = f"    {quote(name)} serial"
        else:
            definition += f" DEFAULT {default}"
    elif default is not None:
        definition += f" DEFAULT {default}"
    if not_null:
        definition += " NOT NULL"
    return definition


def render_table(cursor, table: str) -> str:
    table_oid = get_table_oid(cursor, table)
    definitions = [render_column(column) for column in get_columns(cursor, table_oid)]
    for name, _constraint_type, definition in get_constraints(cursor, table_oid):
        definitions.append(f"    CONSTRAINT {quote(name)} {definition}")

    qualified_table = f"{quote(SCHEMA)}.{quote(table)}"
    lines = [
        "-- Generated from the connected PostgreSQL database.",
        f"-- Table: {qualified_table}",
        "",
        f"CREATE TABLE {qualified_table} (",
        ",\n".join(definitions),
        ");",
    ]
    indexes = get_indexes(cursor, table_oid)
    if indexes:
        lines.extend(["", "-- Indexes", *(f"{index};" for index in indexes)])
    lines.append("")
    return "\n".join(lines)


def main():
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    with connection.cursor() as cursor:
        tables = get_tables(cursor)
        order = topological_order(get_dependencies(cursor, tables))
        for table in tables:
            (OUTPUT_DIR / f"{table}.sql").write_text(render_table(cursor, table), encoding="utf-8")

    order_lines = [
        "# PostgreSQL table creation files",
        "",
        "Each `.sql` file contains the `CREATE TABLE`, constraints, and indexes for one table in the connected database.",
        "Run the files against an empty PostgreSQL database in this dependency-safe order:",
        "",
        *(f"{index}. `{table}.sql`" for index, table in enumerate(order, start=1)),
        "",
        "Regenerate after schema changes:",
        "",
        "```powershell",
        ".\\.venv\\Scripts\\python.exe tools\\export_database_schema.py",
        "```",
        "",
    ]
    (OUTPUT_DIR / "README.md").write_text("\n".join(order_lines), encoding="utf-8")
    print(f"Generated {len(tables)} table files in {OUTPUT_DIR}")


if __name__ == "__main__":
    main()
