# Generated by Django 5.2.16 on 2026-07-25 14:35

from django.db import migrations, models


def mark_previously_replied_contacts_as_contacted(apps, schema_editor):
    ContactSubmission = apps.get_model("contact", "ContactSubmission")
    ContactSubmission.objects.filter(
        status="in_progress",
        handled_at__isnull=False,
    ).update(status="contacted", handled=True)


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactsubmission_handled_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsubmission',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('contacted', 'Contacted'), ('handled', 'Handled'), ('spam', 'Spam')], default='new', max_length=24),
        ),
        migrations.RunPython(
            mark_previously_replied_contacts_as_contacted,
            migrations.RunPython.noop,
        ),
    ]
