import { Link } from "react-router-dom";
import { informationSessionPath } from "./data";
import { isManagedItemActive, useManagedSection } from "@/components/content/ManagedContentProvider";

const topics = [
  ["AI & ANALYTICS","AI-enabled forecasting","Human judgement, validation, explainability and accountable use of automated outputs.","ri-brain-line"],
  ["SCHEDULE","Schedule reliability","Baseline credibility, progress quality, forecast accuracy and recovery decision-making.","ri-calendar-check-line"],
  ["INTEGRATION","Cost and schedule integration","Connected evidence for commitments, progress, forecasts and decision support.","ri-links-line"],
  ["RISK","Risk, change and contingency","Uncertainty, change discipline, confidence levels and defensible contingency practice.","ri-scales-3-line"],
  ["DATA","Data quality and assurance","Provenance, governance, reconciliation, controls maturity and reporting confidence.","ri-database-2-line"],
  ["PUBLIC VALUE","Carbon and sustainability controls","Making time, cost, risk and environmental consequences visible together.","ri-leaf-line"],
];

export default function ContributeResearch(){const section=useManagedSection("research",{eyebrow:"Applied Research & Innovation",status:"Future funding call — register interest",title:"Fund the evidence that moves project controls forward.",description:"IPC can create a specialist annual call connecting researchers and practitioners with live project-controls questions, professional audiences and publication routes.",cta_label:"Register research interest",cta_url:informationSessionPath,notice:"Funding value, dates and formal eligibility will be published only after approval.",items:topics.map(([label,title,description,icon])=>({label,title,description,icon}))});return <section className="bg-background-950 section-padding text-background-50"><div className="container-content"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div className="reveal lg:sticky lg:top-28 lg:self-start"><span className="eyebrow text-primary-400">{section.eyebrow}</span><span className="mt-5 inline-block border border-primary-500/40 bg-primary-500/10 px-3 py-1 font-mono text-[10px] font-bold uppercase tracking-widest text-primary-300">{section.status}</span><h2 className="mt-6 font-heading text-[clamp(2.5rem,5vw,4.5rem)] font-semibold leading-[.98] tracking-[-.04em]">{section.title}</h2><p className="mt-7 max-w-xl leading-[1.8] text-background-300">{section.description}</p><Link to={section.cta_url} state={{enquiry:"Applied Research & Innovation"}} className="btn-primary mt-8">{section.cta_label}</Link><p className="mt-5 text-xs leading-relaxed text-background-500">{section.notice}</p></div><div className="reveal grid gap-4 sm:grid-cols-2">{section.items.filter(isManagedItemActive).map(({label,title,description,icon},index)=><article key={title} className="min-h-64 card-hover border border-background-800 bg-background-900/70 p-6"><div className="flex items-center justify-between"><span className="font-mono text-[10px] font-bold tracking-widest text-primary-400">0{index+1} / {label}</span><i className={`${icon} text-xl text-primary-400`} /></div><h3 className="mt-10 text-xl font-semibold">{title}</h3><p className="mt-4 text-sm leading-[1.75] text-background-400">{description}</p></article>)}</div></div></div></section>}
