import { useState } from "react";
import { Link } from "react-router-dom";
import { useManagedSection } from "@/components/content/ManagedContentProvider";
import { informationSessionPath } from "./data";

type Answers={objective?:string;audience?:string;support?:string};
const questions=[
  {key:"objective" as const,label:"What is the primary objective?",options:[["Widen access","access"],["Build capability","capability"],["Support regional skills","regional"],["Recognise excellence","recognition"],["Advance knowledge","knowledge"]]},
  {key:"audience" as const,label:"Who should benefit most?",options:[["Learners and career changers","learners"],["Practitioners and members","practitioners"],["Regional community","community"],["Researchers and academics","research"],["Employers and teams","employers"]]},
  {key:"support" as const,label:"How would you like to contribute?",options:[["Programme funding","programme"],["Funded places","places"],["Mentors or speakers","mentors"],["Venue or hosting","venue"],["Combined partnership","combined"]]},
];
function resultFor(a:Answers){if(a.objective==="access"||a.audience==="learners")return ["Learner Access Fund","Support a defined learner group through scholarships, bursaries, learning access and professional-development opportunities."];if(a.objective==="regional"||a.audience==="community")return ["Regional Skills Fund","Support local talks, mentoring, learner activity, site visits and regional professional capability."];if(a.objective==="recognition")return ["Awards & Recognition Fund","Support awards, prizes, finalist profiles and emerging-talent recognition while protecting independent judging."];if(a.objective==="knowledge"||a.audience==="research")return ["Research & Knowledge Fund","Support applied research, publications, case studies and evidence-led professional knowledge."];return ["Professional Learning Fund","Support Master Classes, mentoring, CPD access and technical-learning activity for practitioners and teams."]}
export default function ContributeRouteBuilder(){const [answers,setAnswers]=useState<Answers>({});const [result,setResult]=useState<string[]|null>(null);const [error,setError]=useState(false);const section=useManagedSection("route_builder",{eyebrow:"Impact route builder",title:"What change does your organisation want to fund?",description:"Answer three questions to generate an indicative starting route.",button_label:"Build recommended route"});function build(){if(!answers.objective||!answers.audience||!answers.support){setError(true);setResult(null);return}setError(false);setResult(resultFor(answers))}return <section className="bg-background-950 section-padding text-background-50"><div className="container-content grid gap-14 lg:grid-cols-[.8fr_1.2fr]"><div className="reveal"><span className="eyebrow text-primary-400">{section.eyebrow}</span><h2 className="mt-5 font-heading text-4xl font-semibold leading-tight md:text-5xl">{section.title}</h2><p className="mt-6 max-w-xl text-lg leading-relaxed text-background-300">{section.description}</p></div><div className="reveal bg-background-50 p-7 text-background-950 md:p-10">{questions.map((q)=><fieldset key={q.key} className="mb-6 border-b border-background-300 pb-6"><legend className="mb-3 font-semibold">{q.label}</legend><div className="flex flex-wrap gap-2">{q.options.map(([label,value])=><button key={value} type="button" aria-pressed={answers[q.key]===value} onClick={()=>setAnswers((current)=>({...current,[q.key]:value}))} className={`border px-3 py-2 text-sm font-medium ${answers[q.key]===value?"border-background-950 bg-background-950 text-background-50":"border-background-300 hover:border-primary-500"}`}>{label}</button>)}</div></fieldset>)}<button type="button" onClick={build} className="btn-primary">{section.button_label}</button><div aria-live="polite">{error&&<div className="mt-6 border-l-2 border-primary-500 bg-background-100 p-5"><h3 className="font-semibold">Complete all three questions</h3><p className="mt-2 text-sm text-foreground-600">Choose one answer in each section so the page can recommend the strongest starting route.</p></div>}{result&&<div className="mt-6 border-l-2 border-primary-500 bg-background-100 p-5"><h3 className="text-lg font-semibold">{result[0]}</h3><p className="mt-2 text-sm leading-relaxed text-foreground-600">{result[1]}</p><Link to={informationSessionPath} state={{enquiry:result[0]}} className="mt-4 inline-flex items-center gap-2 text-sm font-semibold text-primary-700">Start the conversation<i className="ri-arrow-right-line" /></Link></div>}</div></div></div></section>}
