const principles=[
  ["Purpose before promotion","The supported professional outcome should lead the partnership—not logo placement or sales activity."],
  ["Independent recognition","Funders must not influence membership grades, scholarship eligibility, judging or professional-review decisions."],
  ["Consent and privacy","Funding does not provide automatic access to private learner, member, nominee or attendee information."],
  ["Transparent visibility","Commercial support, acknowledgements and sponsored content should be disclosed clearly."],
  ["Evidence-led impact","Reports should distinguish activities, outputs, outcomes and longer-term impact without exaggeration."],
  ["Responsible partnership","Funding should align with integrity, competence, accountability, technology responsibility and public value."],
];

export default function ContributePrinciples(){return <section className="bg-background-50 section-padding"><div className="container-content grid gap-14 lg:grid-cols-12"><div className="lg:col-span-5 lg:sticky lg:top-28 lg:self-start"><div className="flex items-center gap-4"><span className="h-px w-10 bg-primary-500"/><span className="eyebrow text-primary-600">Funding principles</span></div><h2 className="mt-7 font-heading text-[clamp(2.5rem,5vw,4.5rem)] font-semibold leading-[.98] tracking-[-.045em] text-background-950">Prestige, impact and professional trust must move together.</h2><p className="mt-8 max-w-lg text-base leading-[1.8] text-foreground-600">Funding should strengthen the profession without weakening independence, privacy or the credibility of recognition.</p></div><ol className="border-t border-background-300 lg:col-span-7">{principles.map(([title,copy],index)=><li key={title} className="group grid grid-cols-[3rem_1fr_auto] gap-4 border-b border-background-300 py-6 md:py-7"><span className="flex h-11 w-11 items-center justify-center rounded-full bg-background-950 font-mono text-[10px] font-bold text-primary-400 transition-colors group-hover:bg-primary-500 group-hover:text-background-950">0{index+1}</span><div><h3 className="text-lg font-semibold text-background-950 md:text-xl">{title}</h3><p className="mt-2 text-sm leading-relaxed text-foreground-600 md:text-base">{copy}</p></div><i className="ri-shield-check-line mt-2 text-primary-600" /></li>)}</ol></div></section>}
