import { useState } from "react";
import SectionHeader from "@/components/base/SectionHeader";
const faqs=[
  ["What can the IPC Professional Impact Fund support?","Potential routes include scholarships, bursaries, learner access, Master Classes, mentoring, regional clubs, awards, professional publications, research and community activity."],
  ["Are fixed funding packages or prices published?","No. The catalogue does not include pricing or fee schedules. Funding scope should be discussed by email and designed around the programme, audience and intended outcome."],
  ["Does funding guarantee membership or professional recognition?","No. Funding and recognition are separate. Membership grades, scholarship eligibility, awards and professional-review outcomes remain subject to their own criteria and independent decisions."],
  ["Can a funder access learner or member data?","Not automatically. Any information sharing should be transparent, proportionate, consent-based and aligned with privacy obligations and Institute values."],
  ["How will professional impact be reported?","Reporting can cover delivery, participation, access created, capability developed, progression and agreed public-value outcomes while protecting personal and confidential information."],
  ["What information should a funding enquiry include?","Include the organisation, main contact, intended beneficiary group, programme interest, funding objective, proposed support and the professional or social outcome you want to create."],
];
export default function ContributeFaq(){const[open,setOpen]=useState<number|null>(0);return <section className="bg-background-100 section-padding"><div className="container-content grid gap-12 lg:grid-cols-12"><div className="reveal lg:col-span-5"><SectionHeader eyebrow="Funding questions" title="Clear answers before starting a funding conversation." subtitle="Understand scope, pricing, recognition, privacy, impact and partner visibility."/></div><div className="reveal space-y-3 lg:col-span-7">{faqs.map(([question,answer],index)=>{const expanded=open===index;return <article key={question} className="border border-background-300 bg-background-50"><h3><button type="button" aria-expanded={expanded} aria-controls={`fund-faq-${index}`} onClick={()=>setOpen(expanded?null:index)} className="flex w-full items-center justify-between gap-5 p-5 text-left font-semibold focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-primary-500"><span>{question}</span><i className={`${expanded?"ri-subtract-line":"ri-add-line"} text-primary-700`}/></button></h3>{expanded&&<div id={`fund-faq-${index}`} className="px-5 pb-5"><p className="text-sm leading-[1.75] text-foreground-600">{answer}</p></div>}</article>})}</div></div></section>}
