const metrics=[
  ["—","Funded places awarded","Published after the first approved cycle."],
  ["—","Learning or mentoring completions","Reported after delivery."],
  ["—","Research outputs supported","Subject to review and publication."],
  ["—","Progression outcomes","Reported proportionately and with consent."],
];
const assurance=[
  ["01 / SCOPE","Clear purpose and boundaries","Define what is being funded, who benefits, what is excluded and what success should mean."],
  ["02 / GOVERNANCE","Responsibilities and approvals","Confirm decision routes, ownership, safeguarding, conflicts and communication responsibilities."],
  ["03 / PERFORMANCE","Proportionate evidence","Track delivery, participation, outputs and professional outcomes without creating unnecessary burden."],
  ["04 / TRANSPARENCY","Honest impact reporting","Report what happened, what changed, what remains uncertain and what should improve next."],
];
export default function ContributeAssurance(){return <section className="bg-background-950 section-padding text-background-50"><div className="container-content"><div className="grid gap-14 lg:grid-cols-12"><div className="reveal lg:col-span-5"><span className="eyebrow text-primary-400">Accountability and assurance</span><h2 className="mt-5 font-heading text-[clamp(2.5rem,5vw,4.5rem)] font-semibold leading-[.98] tracking-[-.04em]">Fund impact with professional discipline.</h2><p className="mt-8 max-w-xl text-base leading-[1.8] text-background-300">Funding should be governed with the same principles project-controls professionals apply to complex delivery: clarity, evidence, assurance and transparent reporting.</p></div><div className="reveal grid gap-4 sm:grid-cols-2 lg:col-span-7">{metrics.map(([value,title,copy])=><article key={title} className="border border-background-800 bg-background-900/70 p-6"><strong className="font-heading text-4xl text-primary-400">{value}</strong><h3 className="mt-5 text-lg font-semibold">{title}</h3><p className="mt-2 text-sm text-background-400">{copy}</p></article>)}</div></div><p className="mt-6 border-l-2 border-primary-500 pl-4 text-xs leading-relaxed text-background-400">No impact figures are invented. Replace each placeholder with verified programme data and a clearly stated reporting period.</p><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{assurance.map(([label,title,copy])=><article key={label} className="min-h-64 border border-background-800 bg-background-900/70 p-6"><span className="font-mono text-[10px] font-bold tracking-widest text-primary-400">{label}</span><h3 className="mt-9 text-xl font-semibold">{title}</h3><p className="mt-4 text-sm leading-[1.75] text-background-400">{copy}</p></article>)}</div></div></section>}
