import { useState } from "react";
import { Link } from "react-router-dom";
import SectionHeader from "@/components/base/SectionHeader";
import { fundRoutes, informationSessionPath, type FundRoute } from "./data";
import { isManagedItemActive, useManagedSection } from "@/components/content/ManagedContentProvider";

export default function ContributeRoutes() {
  const [activeId,setActiveId]=useState<FundRoute["id"]>("learners");
  const section=useManagedSection("routes",{eyebrow:"Professional impact pathways",title:"Choose the outcome your organisation wants to make possible.",description:"Select a funding route to understand the audience, possible support and intended professional impact.",items:fundRoutes.map((route)=>({...route,tab_description:route.tabDescription,design_title:route.designTitle,design_description:route.designDescription,cta_label:route.button,cta_url:informationSessionPath})),notice:"Funding scope, availability and delivery arrangements should be confirmed for each programme. This page does not publish fixed prices, donation amounts or tax-relief claims."});
  const routes=section.items.filter(isManagedItemActive); const active=routes.find((item)=>item.id===activeId)??routes[0]; if(!active)return null;
  return <section id="routes" className="scroll-mt-16 bg-background-100 section-padding"><div className="container-content"><div className="reveal"><SectionHeader eyebrow={section.eyebrow} title={section.title} subtitle={section.description} centered /></div><div className="reveal mt-12 border border-background-300 bg-background-50 md:mt-16"><div role="tablist" aria-label="Professional impact pathways" className="grid sm:grid-cols-2 lg:grid-cols-5">{routes.map((route)=>{const selected=active.id===route.id;return <button key={route.id} type="button" role="tab" aria-selected={selected} aria-controls="fund-route-panel" onClick={()=>setActiveId(route.id as FundRoute["id"])} className={`min-h-24 border-b border-r border-background-300 p-4 text-left transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-primary-500 ${selected?"bg-background-950 text-background-50":"hover:bg-background-100"}`}><strong className={selected?"text-primary-300":"text-primary-700"}>{route.tab}</strong><span className={`mt-1 block text-xs ${selected?"text-background-400":"text-foreground-500"}`}>{route.tab_description}</span></button>})}</div><div id="fund-route-panel" role="tabpanel" className="grid lg:grid-cols-[1.18fr_.82fr]"><div className="p-6 md:p-10"><span className="eyebrow text-primary-700">{active.eyebrow}</span><h3 className="mt-4 max-w-3xl font-heading text-3xl font-semibold leading-tight text-background-950 md:text-4xl">{active.title}</h3><p className="mt-5 max-w-3xl leading-[1.8] text-foreground-600">{active.description}</p><dl className="mt-8 grid border-l border-t border-background-300 md:grid-cols-3">{[["Who benefits",active.audience],["What funding may support",active.support],["Professional outcome",active.outcome]].map(([label,value])=><div key={label} className="border-b border-r border-background-300 p-5"><dt className="text-xs font-bold uppercase tracking-wider text-primary-700">{label}</dt><dd className="mt-3 text-sm leading-relaxed text-foreground-600">{value}</dd></div>)}</dl></div><aside className="flex flex-col justify-between bg-background-950 p-7 text-background-50 md:p-10"><div><span className="eyebrow text-primary-300">Funding design</span><h3 className="mt-4 text-2xl font-semibold">{active.design_title}</h3><p className="mt-4 text-sm leading-relaxed text-background-300">{active.design_description}</p><p className="mt-6 border border-background-800 bg-background-900 p-4 text-xs leading-relaxed text-background-400">{active.note}</p></div><Link to={active.cta_url} state={{enquiry:active.eyebrow}} className="btn-primary mt-8 w-fit">{active.cta_label}<i className="ri-arrow-right-line" /></Link></aside></div></div><p className="mt-5 border-l-2 border-primary-500 pl-4 text-xs leading-relaxed text-foreground-500">{section.notice}</p></div></section>;
}
