import { isManagedItemActive, useManagedSection } from "@/components/content/ManagedContentProvider";

const fallbackItems = [
  {label:"01 / ACCESS",title:"Remove barriers to entry",description:"Help learners, career changers, veterans, community leaders and people facing employment barriers access professional opportunity."},
  {label:"02 / CAPABILITY",title:"Strengthen workforce skills",description:"Support technical learning, mentoring, CPD, professional recognition and clearer career progression."},
  {label:"03 / KNOWLEDGE",title:"Fund evidence that travels",description:"Enable applied research, articles, case studies, professional publications and knowledge-sharing activity."},
  {label:"04 / COMMUNITY",title:"Build local and national networks",description:"Support regional clubs, Master Classes, mentoring, employer engagement and professional exchange."},
];

export default function ContributePurpose() {
  const section=useManagedSection("purpose",{eyebrow:"Why fund project controls",title:"Better projects begin with better professional capability.",description:"Project-controls professionals test assumptions, interpret variance, forecast outcomes and help leaders act before problems become irreversible.",supporting_text:"Funding access to learning, recognition, mentoring and community helps the profession develop the people and judgement required for more reliable project decisions.",cta_label:"Explore funding routes",cta_url:"#routes",items:fallbackItems});
  return <section className="border-b border-background-200/70 bg-background-50 section-padding"><div className="container-content grid gap-14 lg:grid-cols-12 lg:gap-10"><div className="lg:col-span-5 lg:sticky lg:top-28 lg:self-start"><div className="flex items-center gap-4"><span className="h-px w-10 bg-primary-500" /><span className="eyebrow text-primary-600">{section.eyebrow}</span></div><h2 className="mt-7 max-w-xl font-heading text-[clamp(2.5rem,5vw,4.75rem)] font-semibold leading-[.98] tracking-[-.045em] text-background-950">{section.title}</h2><p className="mt-8 max-w-lg text-base leading-[1.8] text-foreground-600">{section.description}</p><p className="mt-4 max-w-lg text-base leading-[1.8] text-foreground-600">{section.supporting_text}</p><a href={section.cta_url} className="btn-primary mt-8">{section.cta_label}</a></div><ol className="border-t border-background-300 lg:col-span-7">{section.items.filter(isManagedItemActive).map(({label,title,description}) => <li key={label} className="group grid grid-cols-[3.5rem_1fr] gap-5 border-b border-background-300 py-7"><span className="flex h-11 w-11 items-center justify-center rounded-full bg-background-950 font-mono text-[10px] font-bold text-primary-400 transition-colors group-hover:bg-primary-500 group-hover:text-background-950">{label.slice(0,2)}</span><div><span className="font-mono text-[10px] font-bold tracking-widest text-primary-700">{label}</span><h3 className="mt-2 text-xl font-semibold text-background-950">{title}</h3><p className="mt-2 text-sm leading-relaxed text-foreground-600 md:text-base">{description}</p></div></li>)}</ol></div></section>;
}
