const purposes = [
  ["01 / ACCESS", "Remove barriers to entry", "Help learners, career changers, veterans, community leaders and people facing employment barriers access professional opportunity."],
  ["02 / CAPABILITY", "Strengthen workforce skills", "Support technical learning, mentoring, CPD, professional recognition and clearer career progression."],
  ["03 / KNOWLEDGE", "Fund evidence that travels", "Enable applied research, articles, case studies, professional publications and knowledge-sharing activity."],
  ["04 / COMMUNITY", "Build local and national networks", "Support regional clubs, Master Classes, mentoring, employer engagement and professional exchange."],
];

export default function ContributePurpose() {
  return <section className="border-b border-background-200/70 bg-background-50 section-padding"><div className="container-content grid gap-14 lg:grid-cols-12 lg:gap-10"><div className="lg:col-span-5 lg:sticky lg:top-28 lg:self-start"><div className="flex items-center gap-4"><span className="h-px w-10 bg-primary-500" /><span className="eyebrow text-primary-600">Why fund project controls</span></div><h2 className="mt-7 max-w-xl font-heading text-[clamp(2.5rem,5vw,4.75rem)] font-semibold leading-[.98] tracking-[-.045em] text-background-950">Better projects begin with better professional capability.</h2><p className="mt-8 max-w-lg text-base leading-[1.8] text-foreground-600">Project-controls professionals test assumptions, interpret variance, forecast outcomes and help leaders act before problems become irreversible.</p><p className="mt-4 max-w-lg text-base leading-[1.8] text-foreground-600">Funding access to learning, recognition, mentoring and community helps the profession develop the people and judgement required for more reliable project decisions.</p><a href="#routes" className="btn-primary mt-8">Explore funding routes</a></div><ol className="border-t border-background-300 lg:col-span-7">{purposes.map(([id,title,copy]) => <li key={id} className="group grid grid-cols-[3.5rem_1fr] gap-5 border-b border-background-300 py-7"><span className="flex h-11 w-11 items-center justify-center rounded-full bg-background-950 font-mono text-[10px] font-bold text-primary-400 transition-colors group-hover:bg-primary-500 group-hover:text-background-950">{id.slice(0,2)}</span><div><span className="font-mono text-[10px] font-bold tracking-widest text-primary-700">{id}</span><h3 className="mt-2 text-xl font-semibold text-background-950">{title}</h3><p className="mt-2 text-sm leading-relaxed text-foreground-600 md:text-base">{copy}</p></div></li>)}</ol></div></section>;
}
