# Generated by Django 5.2.16 on 2026-07-23 07:20

import django.db.models.deletion
import ipc_backend.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FundContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(default='main', max_length=40, unique=True)),
                ('hero', models.JSONField(default=dict, validators=[ipc_backend.validators.validate_content_section])),
                ('purpose', models.JSONField(default=dict, validators=[ipc_backend.validators.validate_content_section])),
                ('programmes', models.JSONField(default=dict, validators=[ipc_backend.validators.validate_content_section])),
                ('routes', models.JSONField(default=dict, validators=[ipc_backend.validators.validate_content_section])),
                ('applicant_matcher', models.JSONField(default=dict, validators=[ipc_backend.validators.validate_content_section])),
                ('impact', models.JSONField(default=dict, validators=[ipc_backend.validators.validate_content_section])),
                ('research', models.JSONField(default=dict, validators=[ipc_backend.validators.validate_content_section])),
                ('employer', models.JSONField(default=dict, validators=[ipc_backend.validators.validate_content_section])),
                ('partners', models.JSONField(default=dict, validators=[ipc_backend.validators.validate_content_section])),
                ('principles', models.JSONField(default=dict, validators=[ipc_backend.validators.validate_content_section])),
                ('route_builder', models.JSONField(default=dict, validators=[ipc_backend.validators.validate_content_section])),
                ('governance', models.JSONField(default=dict, validators=[ipc_backend.validators.validate_content_section])),
                ('process', models.JSONField(default=dict, validators=[ipc_backend.validators.validate_content_section])),
                ('assurance', models.JSONField(default=dict, validators=[ipc_backend.validators.validate_content_section])),
                ('faq', models.JSONField(default=dict, validators=[ipc_backend.validators.validate_content_section])),
                ('final_cta', models.JSONField(default=dict, validators=[ipc_backend.validators.validate_content_section])),
                ('seo', models.JSONField(default=dict, validators=[ipc_backend.validators.validate_content_section])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_fund_content', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fund Content',
                'verbose_name_plural': 'Fund Content',
                'db_table': 'fund_content',
            },
        ),
    ]
