# Generated by Django 5.2.16 on 2026-07-25 07:59

import ipc_backend.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0002_seed_fund_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundcontent',
            name='individual_support',
            field=models.JSONField(default=dict, validators=[ipc_backend.validators.validate_content_section]),
        ),
    ]
