# Generated by Django 5.2.16 on 2026-07-25 08:04

import ipc_backend.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0003_fundcontent_individual_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundcontent',
            name='individual_support',
            field=models.JSONField(blank=True, default=dict, validators=[ipc_backend.validators.validate_content_section]),
        ),
    ]
