# Generated by Django 5.2.15 on 2026-07-09 08:34

import django.db.models.deletion
import ipc_backend.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under review'), ('more_info_required', 'More information required'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=32)),
                ('grade', models.CharField(choices=[('AffIPC', 'Affiliate Member / AffIPC'), ('MIPC', 'Professional Member / MIPC'), ('AFIPC_L3', 'Associate Fellow Level 3 / AFIPC L3'), ('AFIPC_L4', 'Associate Fellow Level 4 / AFIPC L4'), ('FIPC', 'Fellow / FIPC')], max_length=16)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=80)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('job_title', models.CharField(blank=True, max_length=160)),
                ('organisation', models.CharField(blank=True, max_length=180)),
                ('years_experience', models.CharField(blank=True, max_length=80)),
                ('professional_background', models.TextField()),
                ('professional_statement', models.TextField()),
                ('cpd_evidence', models.TextField(blank=True)),
                ('work_evidence', models.TextField(blank=True)),
                ('references_text', models.TextField(blank=True)),
                ('code_of_conduct_consent', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('cv', 'CV / role summary'), ('cpd', 'CPD evidence'), ('work', 'Work evidence'), ('references', 'References'), ('other', 'Other evidence')], default='other', max_length=24)),
                ('file', models.FileField(upload_to=ipc_backend.validators.evidence_upload_to, validators=[ipc_backend.validators.validate_upload])),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_files', to='applications.membershipapplication')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewerNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_notes', to='applications.membershipapplication')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='membershipapplication',
            index=models.Index(fields=['status', 'grade', 'created_at'], name='application_status_0c2cae_idx'),
        ),
    ]
