# Generated by Django 5.2.15 on 2026-07-09 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('memberships', '0002_membershipgradebenefit_membershipgraderequirement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('organisation', models.CharField(blank=True, max_length=180)),
                ('relationship', models.CharField(blank=True, max_length=160)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('submitted', 'Submitted'), ('under_review', 'Under review'), ('more_info_required', 'More information required'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=32, null=True)),
                ('to_status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under review'), ('more_info_required', 'More information required'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=32)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='applicationevidence',
            name='content_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='applicationevidence',
            name='file_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='applicationevidence',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_application_evidence', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='application_reference',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='membership_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='memberships.membershipgrade'),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='privacy_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reviewernote',
            name='is_internal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='applicationevidence',
            index=models.Index(fields=['application', 'evidence_type'], name='application_applica_195612_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationevidence',
            index=models.Index(fields=['uploaded_at'], name='application_uploade_63ce82_idx'),
        ),
        migrations.AddIndex(
            model_name='membershipapplication',
            index=models.Index(fields=['email'], name='application_email_3716f4_idx'),
        ),
        migrations.AddIndex(
            model_name='membershipapplication',
            index=models.Index(fields=['application_reference'], name='application_applica_074bae_idx'),
        ),
        migrations.AddIndex(
            model_name='membershipapplication',
            index=models.Index(fields=['reviewed_by'], name='application_reviewe_e1b2dd_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewernote',
            index=models.Index(fields=['application', 'created_at'], name='application_applica_31b183_idx'),
        ),
        migrations.AddField(
            model_name='applicationreference',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='applications.membershipapplication'),
        ),
        migrations.AddField(
            model_name='applicationstatushistory',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='applications.membershipapplication'),
        ),
        migrations.AddField(
            model_name='applicationstatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='applicationreference',
            index=models.Index(fields=['application'], name='application_applica_58c801_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationstatushistory',
            index=models.Index(fields=['application', 'created_at'], name='application_applica_1aaa33_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationstatushistory',
            index=models.Index(fields=['to_status', 'created_at'], name='application_to_stat_8c9938_idx'),
        ),
    ]
