# Generated by Django 5.2.16 on 2026-07-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_application_architecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationevidence',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
