# Generated by Django 5.2.16 on 2026-07-15 11:00

from django.db import migrations, models


def normalise_legacy_statuses(apps, schema_editor):
    Application = apps.get_model("applications", "Application")
    ApplicationStatusHistory = apps.get_model(
        "applications",
        "ApplicationStatusHistory",
    )
    legacy_statuses = ("more_info_required", "rejected")
    Application.objects.filter(status__in=legacy_statuses).update(
        status="under_review"
    )
    ApplicationStatusHistory.objects.filter(
        from_status__in=legacy_statuses
    ).update(from_status="under_review")
    ApplicationStatusHistory.objects.filter(
        to_status__in=legacy_statuses
    ).update(to_status="under_review")


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_applicationevidence_updated_at'),
    ]

    operations = [
        migrations.RunPython(
            normalise_legacy_statuses,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved')], default='submitted', max_length=32),
        ),
        migrations.AlterField(
            model_name='applicationstatushistory',
            name='from_status',
            field=models.CharField(blank=True, choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='applicationstatushistory',
            name='to_status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved')], max_length=32),
        ),
    ]
