# Generated by Django 5.2.16 on 2026-07-15 11:45

import django.db.models.deletion
import logging
from django.conf import settings
from django.db import migrations, models


logger = logging.getLogger(__name__)


def backfill_reliable_approved_users(apps, schema_editor):
    User = apps.get_model("auth", "User")
    Application = apps.get_model("applications", "Application")
    linked_user_ids = set(
        Application.objects.exclude(approved_user_id=None).values_list(
            "approved_user_id",
            flat=True,
        )
    )

    for application in Application.objects.filter(
        status="approved",
        approved_user_id=None,
    ).iterator():
        matches = list(
            User.objects.filter(
                email__iexact=application.email,
                is_staff=False,
            ).exclude(pk__in=linked_user_ids)[:2]
        )
        approved_at = application.reviewed_at or application.updated_at
        updates = {
            "approved_at": approved_at,
            "approved_by_id": application.reviewed_by_id,
        }
        if len(matches) == 1:
            user = matches[0]
            updates.update({
                "approved_user_id": user.pk,
                "account_created_at": user.date_joined,
            })
            linked_user_ids.add(user.pk)
        else:
            logger.warning(
                "Approved application %s was not linked during migration: %s reliable user matches.",
                application.pk,
                len(matches),
            )
        Application.objects.filter(pk=application.pk).update(**updates)


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_alter_application_status_and_more'),
        ('accounts', '0003_user_email_ci_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='account_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_membership_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='approved_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_application', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='welcome_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(
            backfill_reliable_approved_users,
            migrations.RunPython.noop,
        ),
    ]
