# Generated by Django 5.2.16 on 2026-07-15 13:13

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_application_account_created_at_and_more'),
        ('memberships', '0004_membership_grade_presentation_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='username',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('username'), condition=models.Q(('username', ''), _negated=True), name='uniq_application_username_ci'),
        ),
    ]
