# Generated by Django 5.2.16 on 2026-07-28 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_validate_uk_telephone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='current_step',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('more_info_required', 'Additional Information Required'), ('approved', 'Approved'), ('refused', 'Refused'), ('withdrawn', 'Withdrawn')], default='submitted', max_length=32),
        ),
        migrations.AlterField(
            model_name='applicationstatushistory',
            name='from_status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('more_info_required', 'Additional Information Required'), ('approved', 'Approved'), ('refused', 'Refused'), ('withdrawn', 'Withdrawn')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='applicationstatushistory',
            name='to_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('more_info_required', 'Additional Information Required'), ('approved', 'Approved'), ('refused', 'Refused'), ('withdrawn', 'Withdrawn')], max_length=32),
        ),
    ]
