# Generated by Django 5.2.16 on 2026-07-28 08:53

import django.db.models.deletion
import ipc_backend.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('awards', '0012_sync_preview_13_awards_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('summary', models.TextField()),
                ('description', models.TextField()),
                ('location', models.CharField(db_index=True, max_length=160)),
                ('specialism', models.CharField(blank=True, max_length=160)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('summary', models.TextField()),
                ('provider', models.CharField(max_length=180)),
                ('external_url', models.URLField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DiscussionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='user_panel.club')),
            ],
        ),
        migrations.CreateModel(
            name='DiscussionThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=220)),
                ('body', models.TextField(max_length=10000)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_threads', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='threads', to='user_panel.discussioncategory')),
            ],
            options={
                'ordering': ['-is_pinned', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscussionPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(max_length=10000)),
                ('is_edited', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_posts', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='user_panel.discussionpost')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='user_panel.discussionthread')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProgrammeEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('message', models.TextField(max_length=5000)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('more_info_required', 'Additional information required'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='submitted', max_length=32)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programme_enquiries', to=settings.AUTH_USER_MODEL)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enquiries', to='user_panel.programme')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('summary', models.TextField()),
                ('description', models.TextField()),
                ('category', models.CharField(db_index=True, max_length=120)),
                ('eligibility', models.TextField()),
                ('funding_min_percent', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('funding_max_percent', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('partner_name', models.CharField(blank=True, max_length=180)),
                ('partner_url', models.URLField(blank=True, max_length=500)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('form_fields', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['deadline', 'title'],
                'indexes': [models.Index(fields=['is_active', 'deadline'], name='user_panel__is_acti_8066e1_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('funding_min_percent__isnull', True), ('funding_min_percent__lte', 100), _connector='OR'), name='scholarship_min_lte_100'), models.CheckConstraint(condition=models.Q(('funding_max_percent__isnull', True), ('funding_max_percent__lte', 100), _connector='OR'), name='scholarship_max_lte_100')],
            },
        ),
        migrations.CreateModel(
            name='ScholarshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('more_info_required', 'Additional information required'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='draft', max_length=32)),
                ('current_step', models.PositiveSmallIntegerField(default=1)),
                ('statement', models.TextField(blank=True, max_length=6000)),
                ('responses', models.JSONField(blank=True, default=dict)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarship_applications', to=settings.AUTH_USER_MODEL)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='user_panel.scholarship')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('category', models.CharField(max_length=32)),
                ('subject', models.CharField(max_length=180)),
                ('status', models.CharField(default='open', max_length=32)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(max_length=8000)),
                ('attachment', models.FileField(blank=True, upload_to='user-panel/support/%Y/%m/', validators=[ipc_backend.validators.validate_upload])),
                ('is_staff_reply', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='user_panel.supportticket')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=180)),
                ('category', models.CharField(db_index=True, max_length=32)),
                ('file', models.FileField(upload_to='user-panel/documents/%Y/%m/', validators=[ipc_backend.validators.validate_upload])),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('can_delete', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panel_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('notification_type', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=180)),
                ('message', models.TextField(max_length=2000)),
                ('target_url', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panel_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_visibility', models.CharField(choices=[('private', 'Private'), ('members', 'IPC members'), ('public', 'Public')], default='members', max_length=16)),
                ('email_notifications', models.BooleanField(default=True)),
                ('club_communications', models.BooleanField(default=True)),
                ('event_reminders', models.BooleanField(default=True)),
                ('marketing_consent', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='panel_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_name', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('timezone', models.CharField(default='Europe/London', max_length=64)),
                ('biography', models.TextField(blank=True, max_length=3000)),
                ('job_title', models.CharField(blank=True, max_length=160)),
                ('employer', models.CharField(blank=True, max_length=180)),
                ('industry', models.CharField(blank=True, max_length=120)),
                ('years_experience', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('professional_headline', models.CharField(blank=True, max_length=180)),
                ('qualifications', models.TextField(blank=True, max_length=3000)),
                ('certifications', models.TextField(blank=True, max_length=3000)),
                ('linkedin_url', models.URLField(blank=True, max_length=500)),
                ('website_url', models.URLField(blank=True, max_length=500)),
                ('interests', models.ManyToManyField(blank=True, related_name='profiles', to='user_panel.professionalinterest')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='panel_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AwardNomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nominee_type', models.CharField(choices=[('self', 'Myself'), ('other', 'Another person')], max_length=12)),
                ('nominee_name', models.CharField(max_length=180)),
                ('nominee_email', models.EmailField(blank=True, max_length=254)),
                ('statement', models.TextField(blank=True, max_length=6000)),
                ('responses', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('more_info_required', 'Additional information required'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='draft', max_length=32)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award_nominations', to=settings.AUTH_USER_MODEL)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nominations', to='awards.awardprogramme')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['applicant', 'status'], name='user_panel__applica_edd81f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClubMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('rejected', 'Rejected'), ('suspended', 'Suspended'), ('left', 'Left')], default='pending', max_length=16)),
                ('role', models.CharField(choices=[('member', 'Member'), ('moderator', 'Moderator')], default='member', max_length=16)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='user_panel.club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'status'], name='user_panel__user_id_e0b8af_idx'), models.Index(fields=['club', 'status'], name='user_panel__club_id_ae4f4d_idx')],
                'constraints': [models.UniqueConstraint(fields=('club', 'user'), name='unique_club_member')],
            },
        ),
        migrations.CreateModel(
            name='ClubMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('body', models.TextField(max_length=4000)),
                ('is_edited', models.BooleanField(default=False)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='user_panel.club')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['club', 'created_at'], name='user_panel__club_id_e1a2e3_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='discussioncategory',
            constraint=models.UniqueConstraint(fields=('club', 'slug'), name='unique_club_category'),
        ),
        migrations.AddIndex(
            model_name='scholarshipapplication',
            index=models.Index(fields=['applicant', 'status'], name='user_panel__applica_70044b_idx'),
        ),
        migrations.AddConstraint(
            model_name='scholarshipapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'withdrawn'), _negated=True), fields=('scholarship', 'applicant'), name='unique_active_scholarship_application'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['requester', 'status'], name='user_panel__request_ba44c0_idx'),
        ),
        migrations.AddIndex(
            model_name='usernotification',
            index=models.Index(fields=['recipient', 'is_read', 'created_at'], name='user_panel__recipie_987d40_idx'),
        ),
    ]
