# Generated by Django 5.2.16 on 2026-07-28 11:52

import django.db.models.deletion
import ipc_backend.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0003_reconcile_interest_relation_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardNominationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='user-panel/award-evidence/%Y/%m/', validators=[ipc_backend.validators.validate_upload])),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('nomination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='user_panel.awardnomination')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
