# Generated by Django 5.2.15 on 2026-07-09 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardsinterest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('closed', 'Closed')], default='new', max_length=24),
        ),
        migrations.CreateModel(
            name='AwardProgramme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('academic', 'Academic'), ('commercial', 'Commercial'), ('professional', 'Professional'), ('other', 'Other')], default='other', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='awards_awar_categor_4f1292_idx'), models.Index(fields=['slug'], name='awards_awar_slug_1d6b47_idx')],
            },
        ),
        migrations.AddField(
            model_name='awardsinterest',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interests', to='awards.awardprogramme'),
        ),
        migrations.AddIndex(
            model_name='awardsinterest',
            index=models.Index(fields=['interest_type', 'created_at'], name='awards_awar_interes_419ad9_idx'),
        ),
        migrations.AddIndex(
            model_name='awardsinterest',
            index=models.Index(fields=['status'], name='awards_awar_status_7e515e_idx'),
        ),
        migrations.AddIndex(
            model_name='awardsinterest',
            index=models.Index(fields=['email'], name='awards_awar_email_c71480_idx'),
        ),
    ]
